apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
      - name: book
        image: bookandinventory.azurecr.io/book:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          value: "postgresql://part4:byJ2Lfp1u2icQfl8voFQSiuWCRixwcmz@dpg-crjao3m8ii6s73fe56q0-a.oregon-postgres.render.com/part4_5g49"
---
apiVersion: v1
kind: Service
metadata:
  name: book
spec:
  selector:
    app: book
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: bookandinventory.azurecr.io/inventory:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        env:
        - name: PORT
          value: "8090"
        - name: DATABASE_URL
          value: "postgresql://part4:byJ2Lfp1u2icQfl8voFQSiuWCRixwcmz@dpg-crjao3m8ii6s73fe56q0-a.oregon-postgres.render.com/part4_5g49"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  selector:
    app: inventory
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
